#!/bin/bash

if [[ $TOOLS_BIN == "" ]]; then
	TOOLS_BIN=$(realpath $(dirname $0))
fi
source ${TOOLS_BIN}/error_codes

if [[ $1 == "-h" ]] || [[ $# -lt 1 ]]; then
	echo usage $1
	echo "  -h: usage message"
	echo "  <device,device....>:  List of devices to check to see if they are mounted"
	exit $E_USAGE
fi

mount_tmp=`mktemp /tmp/mount_temp.XXXXX`
mount | cut -d' ' -f1 > $mount_tmp
#
# Any disk that is an LVM physical volume is in use — even if no
# LV on it is currently mounted.  A benchmark (fio, iozone, etc.)
# writing to that disk would destroy the volume group.
#
if command -v pvs &>/dev/null; then
	for pv in $(pvs --noheadings -o pv_name 2>/dev/null | awk '{print $1}'); do
		echo "$pv" >> $mount_tmp
		pv_base=${pv#/dev/}
		if [[ $pv_base =~ ^nvme || $pv_base =~ ^mmcblk ]]; then
			pv_base=$(echo "$pv_base" | sed 's/p[[:digit:]]*$//')
		else
			pv_base=$(echo "$pv_base" | sed 's/[[:digit:]]*$//')
		fi
		echo "/dev/$pv_base" >> $mount_tmp
	done
fi
#
# Now check for mounted
#
for var in "$@"
do
	grep -qx $var $mount_tmp
	if [ $? -eq 0 ]; then
		rm $mount_tmp
		exit $E_DEVICE_IN_USE
	fi
done
rm $mount_tmp
exit $E_SUCCESS

